spring:
  data:
    mongodb:
      database: threadly_auth
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      authentication-database: admin
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081

app:
  mail:
    from: ${MAIL_FROM:}
    from-name: Threadly
  frontend-url: ${FRONTEND_URL:http://localhost}
  chat-service-url: ${CHAT_SERVICE_URL:http://localhost:8080}
      
security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 604800
    secret: ${JWT_SECRET:}