version: '3.6'
services:
    mongo-chat:
      image: mongo:4.4
      container_name: mongo-chat
      restart: always
      env_file:
        - .env
      environment:
        MONGODB_CHAT_DATABASE: ${MONGODB_CHAT_DATABASE}
      ports:
        - "27018:27017"
