version: '3.6'
services:
    mongo-chat:
      image: mongo:4.4
      container_name: mongo-chat
      restart: always
      environment:
        MONGO_INITDB_DATABASE: threadly_chat_db
      ports:
        - "27018:27017"

    threadly-chat:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: threadly-chat
      ports:
        - "8080:8080"
      depends_on:
        - mongo-chat
      env_file:
        - ../.env
      environment:
        SPRING_DATA_MONGODB_HOST: mongo-chat
        SPRING_DATA_MONGODB_PORT: 27017
      restart: unless-stopped
