version: '3.6'
services:
    mongo-chat:
      image: mongo:4.4
      container_name: mongo-chat
      restart: always
      environment:
        MONGO_INITDB_DATABASE: threadly_chat_db
      ports:
        - "27018:27017"

    threadly-chat:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: threadly-chat
      ports:
        - "8080:8080"
      depends_on:
        - mongo-chat
      environment:
        SPRING_DATA_MONGODB_HOST: mongo-chat
        SPRING_DATA_MONGODB_PORT: 27017
        PUSH_VAPID_PUBLIC_KEY: BDTNP0HsKMQCh2-_pqH7u19OHCEHEjs8yly2Tcj6fEnBXHSBG-cgff4VWyzpwVK2aCN4EqKYiue9jUVupxdvEng
        PUSH_VAPID_PRIVATE_KEY: iErgX_vQ0JfOOCYuyS6sAp5VhT5R3cBBeEupHLyIBks
        PUSH_VAPID_SUBJECT: mailto:admin@example.com
      restart: unless-stopped
